### ISSUE TITLE
listener mode only

### ISSUE THREAD

**Issue by gsm42** [Unit-X/srt_to_udp_server#6]
Hi. Could you advice does this supports SRT listener mode only or would it also work as caller?

**Comment by andersc** [comment]
Hi,

Well..   We use the nomenclature of traditional client/server in this project. This being the server. The server binds to a port (listens on a port) on an interface. Then a client is connecting to that IP/Port and sends data to the server (this project). 

So I'm guessing that would be equivalent to listener..

(does this explanation answer your question?)

/Anders

**Comment by gsm42** [comment]
Hi Yes that's what I've originally thought.
Thanks for confirmation anyway.
